/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.menuJuegos.gui;

import autonoma.menuJuegos.elements.FlappyBird;
import autonoma.menuJuegos.elements.HiloMoverObstaculo;
import autonoma.menuJuegos.elements.Sonido;
import static autonoma.menuJuegos.gui.FlappyBirdGameWindow._HEIGHT;
import static autonoma.menuJuegos.gui.FlappyBirdGameWindow._WIDTH;
import autonoma.menuJuegosBase.elements.GraphicContainer;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.swing.JOptionPane;


/**
 *
 * @author Camila
 */
public class FlappyBirdGameWindow extends javax.swing.JFrame implements GraphicContainer {
    private FlappyBird ventana;
    private GameWindow ventanaPrincipal;
    private Sonido sonido;
    private BufferedImage imagenBuffer;
    private Graphics gImagenBuffer;
    public static final int _WIDTH = 360;
    public static final int _HEIGHT = 640;
    private HiloMoverObstaculo hiloObstaculos;

    /**
     * Creates new form FlappyBird
     */
     public FlappyBirdGameWindow(GameWindow ventanaPrincipal) {
        setUndecorated(true);
        initComponents();
        this.setSize(_WIDTH,_HEIGHT);
        this.setLocationRelativeTo(null);
        this.ventana = new FlappyBird(0, 0, 640, 360, Color.BLACK, this);
        this.sonido = new Sonido();
        this.sonido.reproducir("flappy.wav");
        this.hiloObstaculos = new HiloMoverObstaculo(this.ventana);
        this.hiloObstaculos.start();
        this.ventanaPrincipal = ventanaPrincipal;
        this.setLayout(null);

        this.imagenBuffer = new BufferedImage(this.getWidth(), this.getHeight(), BufferedImage.TYPE_INT_RGB);
        this.gImagenBuffer = this.imagenBuffer.getGraphics();
    }

    private void exitGame() {
      this.hiloObstaculos.stop();
      ventanaPrincipal = new GameWindow ();
      ventanaPrincipal.setVisible(true);
      this.dispose();
    }
    
    public void reiniciar() throws IOException {
        if (this.ventana.isGameOver()) {
            String opcion;
            do {
                if(this.ventana.isGameOver()){
                    this.gameOver();
                }
                opcion = JOptionPane.showInputDialog(null, "¿Deseas reiniciar el juego? 1) sí  2) no");
            } while (!"1".equals(opcion) && !"2".equals(opcion));

            if ("1".equals(opcion)) {
                this.ventana.reiniciar();
                this.setVisible(true);  
                this.repaint();         
            } else if ("2".equals(opcion)) {
                this.hiloObstaculos.stop();
                exitGame(); 
            }
        }
    }
    
    public void gameOver (){
        this.sonido.detenerLoop();
        this.sonido.reproducir("PacmanGameOver.wav");
        JOptionPane.showMessageDialog(null, "Perdiste, tu puntaje fue: " + this.ventana.getPuntaje());
    }
    
    @Override
    public void update(Graphics g){
        gImagenBuffer.setColor(Color.BLACK);
        gImagenBuffer.fillRect(0, 0, imagenBuffer.getWidth(), imagenBuffer.getHeight());
        ventana.paint(gImagenBuffer);
        g.drawImage(imagenBuffer, 0, 0, this);
    }
    
    @Override
    public void paint(Graphics g) { 
        update(g); 
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        this.ventana.handleKey(evt);

        if (evt.getKeyCode() == KeyEvent.VK_Q) {
            exitGame();
        }
        repaint();
    }//GEN-LAST:event_formKeyPressed

    @Override
    public void refresh() {
        this.repaint();
    }

    @Override
    public Rectangle getBoundaries() {
        return this.getBounds();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
