/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.menuJuegos.gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Camila
 */
public class GameWindow extends javax.swing.JFrame {
    public GameWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        juego1 = new javax.swing.JPanel();
        imagenJuego1 = new javax.swing.JLabel();
        juego4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        juego3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        imagenSalir = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenJuego1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/menuJuego/images/flappyBird.jpg"))); // NOI18N
        imagenJuego1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenJuego1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout juego1Layout = new javax.swing.GroupLayout(juego1);
        juego1.setLayout(juego1Layout);
        juego1Layout.setHorizontalGroup(
            juego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego1Layout.createSequentialGroup()
                .addComponent(imagenJuego1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        juego1Layout.setVerticalGroup(
            juego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego1Layout.createSequentialGroup()
                .addComponent(imagenJuego1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelPrincipal.add(juego1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 130, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/menuJuego/images/snake.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout juego4Layout = new javax.swing.GroupLayout(juego4);
        juego4.setLayout(juego4Layout);
        juego4Layout.setHorizontalGroup(
            juego4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        juego4Layout.setVerticalGroup(
            juego4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelPrincipal.add(juego4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 140, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/menuJuego/images/pacman.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout juego3Layout = new javax.swing.GroupLayout(juego3);
        juego3.setLayout(juego3Layout);
        juego3Layout.setHorizontalGroup(
            juego3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        juego3Layout.setVerticalGroup(
            juego3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelPrincipal.add(juego3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 130, 180));

        imagenSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/menuJuego/images/btnSalir.png"))); // NOI18N
        imagenSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addComponent(imagenSalir)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addComponent(imagenSalir)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelPrincipal.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 160, 60));

        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/menuJuego/images/menu.png"))); // NOI18N
        panelPrincipal.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imagenJuego1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenJuego1MouseClicked
        FlappyBirdGameWindow juegoFlappyBird = new FlappyBirdGameWindow(this);
        juegoFlappyBird.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imagenJuego1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        SnakeGameWindow juegoSnake = new SnakeGameWindow(this);
        juegoSnake.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        PacmanGameWindow juegoPacman;
        try {
            juegoPacman = new PacmanGameWindow(this);
            juegoPacman.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(GameWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void imagenSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_imagenSalirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JLabel imagenJuego1;
    private javax.swing.JLabel imagenSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel juego1;
    private javax.swing.JPanel juego3;
    private javax.swing.JPanel juego4;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
